/*
 * HPP
 * Hosted Payment Page
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.api.hosted_payment_page.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.klarna.rest.api.hosted_payment_page.model.HPPMerchantUrlsV1;
import com.klarna.rest.api.hosted_payment_page.model.HPPOptionsV1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * HPPSessionCreationRequestV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-20T10:31:07.217Z")
public class HPPSessionCreationRequestV1 {
  @JsonProperty("merchant_urls")
  private HPPMerchantUrlsV1 merchantUrls = null;

  @JsonProperty("options")
  private HPPOptionsV1 options = null;

  @JsonProperty("payment_session_url")
  private String paymentSessionUrl = null;

  public HPPSessionCreationRequestV1 merchantUrls(HPPMerchantUrlsV1 merchantUrls) {
    this.merchantUrls = merchantUrls;
    return this;
  }

   /**
   * URLs used to redirect the Consumer
   * @return merchantUrls
  **/
  @ApiModelProperty(required = true, value = "URLs used to redirect the Consumer")
  public HPPMerchantUrlsV1 getMerchantUrls() {
    return merchantUrls;
  }

  public void setMerchantUrls(HPPMerchantUrlsV1 merchantUrls) {
    this.merchantUrls = merchantUrls;
  }

  public HPPSessionCreationRequestV1 options(HPPOptionsV1 options) {
    this.options = options;
    return this;
  }

   /**
   * Options
   * @return options
  **/
  @ApiModelProperty(value = "Options")
  public HPPOptionsV1 getOptions() {
    return options;
  }

  public void setOptions(HPPOptionsV1 options) {
    this.options = options;
  }

  public HPPSessionCreationRequestV1 paymentSessionUrl(String paymentSessionUrl) {
    this.paymentSessionUrl = paymentSessionUrl;
    return this;
  }

   /**
   * URL of the KP Session or KCO Order to be hosted by the HPP Session
   * @return paymentSessionUrl
  **/
  @ApiModelProperty(example = "One of https://api.klarna.com/payments/v1/sessions/92d97f60-7a78-46a5-8f68-c56fe52dc4af or https://api.klarna.com/checkout/v3/orders/92d97f60-7a78-46a5-8f68-c56fe52dc4af", required = true, value = "URL of the KP Session or KCO Order to be hosted by the HPP Session")
  public String getPaymentSessionUrl() {
    return paymentSessionUrl;
  }

  public void setPaymentSessionUrl(String paymentSessionUrl) {
    this.paymentSessionUrl = paymentSessionUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HPPSessionCreationRequestV1 sessionCreationRequestV1 = (HPPSessionCreationRequestV1) o;
    return Objects.equals(this.merchantUrls, sessionCreationRequestV1.merchantUrls) &&
        Objects.equals(this.options, sessionCreationRequestV1.options) &&
        Objects.equals(this.paymentSessionUrl, sessionCreationRequestV1.paymentSessionUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantUrls, options, paymentSessionUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HPPSessionCreationRequestV1 {\n");
    
    sb.append("    merchantUrls: ").append(toIndentedString(merchantUrls)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    paymentSessionUrl: ").append(toIndentedString(paymentSessionUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

