/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.api.merchant_card_service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CardServiceSettlementRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-02T14:59:55.645Z")
public class CardServiceSettlementRequest {
  @JsonProperty("promise_id")
  private String promiseId = null;

  @JsonProperty("order_id")
  private String orderId = null;

  @JsonProperty("key_id")
  private String keyId = null;

  public CardServiceSettlementRequest promiseId(String promiseId) {
    this.promiseId = promiseId;
    return this;
  }

   /**
   * Unique identifier for the promise associated to the settlement.
   * @return promiseId
  **/
  @ApiModelProperty(example = "ee4a8e3a-9dfd-49e0-9ac8-ea2b6c76408c", value = "Unique identifier for the promise associated to the settlement.")
  public String getPromiseId() {
    return promiseId;
  }

  public void setPromiseId(String promiseId) {
    this.promiseId = promiseId;
  }

  public CardServiceSettlementRequest orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Unique identifier for the order associated to the settlement.
   * @return orderId
  **/
  @ApiModelProperty(example = "f3392f8b-6116-4073-ab96-e330819e2c07", required = true, value = "Unique identifier for the order associated to the settlement.")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public CardServiceSettlementRequest keyId(String keyId) {
    this.keyId = keyId;
    return this;
  }

   /**
   * Unique identifier for the public key to be used for encryption of the card data.
   * @return keyId
  **/
  @ApiModelProperty(example = "16e4b85e-899b-4427-a39f-07a496e9515b", required = true, value = "Unique identifier for the public key to be used for encryption of the card data.")
  public String getKeyId() {
    return keyId;
  }

  public void setKeyId(String keyId) {
    this.keyId = keyId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardServiceSettlementRequest settlementRequest = (CardServiceSettlementRequest) o;
    return Objects.equals(this.promiseId, settlementRequest.promiseId) &&
        Objects.equals(this.orderId, settlementRequest.orderId) &&
        Objects.equals(this.keyId, settlementRequest.keyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(promiseId, orderId, keyId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardServiceSettlementRequest {\n");
    
    sb.append("    promiseId: ").append(toIndentedString(promiseId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    keyId: ").append(toIndentedString(keyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

