/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.api.merchant_card_service.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * CardServicePromiseCreatedResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-20T11:07:02.754Z")
public class CardServicePromiseCreatedResponse {
  @JsonProperty("expires_at")
  private OffsetDateTime expiresAt = null;

  @JsonProperty("promise_id")
  private String promiseId = null;

  public CardServicePromiseCreatedResponse expiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

   /**
   * Get expiresAt
   * @return expiresAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }

   /**
   * The unique promise ID
   * @return promiseId
  **/
  @ApiModelProperty(example = "ee4a8e3a-9dfd-49e0-9ac8-ea2b6c76408c", value = "The unique promise ID")
  public String getPromiseId() {
    return promiseId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardServicePromiseCreatedResponse promiseCreatedResponse = (CardServicePromiseCreatedResponse) o;
    return Objects.equals(this.expiresAt, promiseCreatedResponse.expiresAt) &&
        Objects.equals(this.promiseId, promiseCreatedResponse.promiseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiresAt, promiseId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardServicePromiseCreatedResponse {\n");
    
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    promiseId: ").append(toIndentedString(promiseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

