/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.api.customer_token.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TokenCardInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-20T10:21:37.701Z")
public class TokenCardInformation {
  @JsonProperty("brand")
  private String brand = null;

  @JsonProperty("expiry_date")
  private String expiryDate = null;

  @JsonProperty("masked_number")
  private String maskedNumber = null;

  public TokenCardInformation brand(String brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Card brand
   * @return brand
  **/
  @ApiModelProperty(example = "VISA", required = true, value = "Card brand")
  public String getBrand() {
    return brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public TokenCardInformation expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Card expiration date
   * @return expiryDate
  **/
  @ApiModelProperty(example = "12/2020", required = true, value = "Card expiration date")
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }

  public TokenCardInformation maskedNumber(String maskedNumber) {
    this.maskedNumber = maskedNumber;
    return this;
  }

   /**
   * Masked credit card number
   * @return maskedNumber
  **/
  @ApiModelProperty(example = "************1234", required = true, value = "Masked credit card number")
  public String getMaskedNumber() {
    return maskedNumber;
  }

  public void setMaskedNumber(String maskedNumber) {
    this.maskedNumber = maskedNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenCardInformation cardInformation = (TokenCardInformation) o;
    return Objects.equals(this.brand, cardInformation.brand) &&
        Objects.equals(this.expiryDate, cardInformation.expiryDate) &&
        Objects.equals(this.maskedNumber, cardInformation.maskedNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brand, expiryDate, maskedNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenCardInformation {\n");
    
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    maskedNumber: ").append(toIndentedString(maskedNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

