/*
 * Customer Tokens
 * The Customer Token API is used to charge customers with a tokenized Klarna payment method and can be used for recurring purchases, subscriptions and for storing a customer's payment method. Tokens are created using the [generate a customer token](#payments-api-generate-a-consumer-token) call in the payments API.
 *
 * OpenAPI spec version: 3.0
 * Contact: developers-experience@klarna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.api.customer_token.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TokenMerchantUrls
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-02T11:40:30.975Z")
public class TokenMerchantUrls {
  @JsonProperty("confirmation")
  private String confirmation = null;

  @JsonProperty("push")
  private String push = null;

  public TokenMerchantUrls confirmation(String confirmation) {
    this.confirmation = confirmation;
    return this;
  }

   /**
   * URL of merchant confirmation page. (max 2000 characters)
   * @return confirmation
  **/
  @ApiModelProperty(required = true, value = "URL of merchant confirmation page. (max 2000 characters)")
  public String getConfirmation() {
    return confirmation;
  }

  public void setConfirmation(String confirmation) {
    this.confirmation = confirmation;
  }

  public TokenMerchantUrls push(String push) {
    this.push = push;
    return this;
  }

   /**
   * URL that will be requested when an order is completed. Should be different than checkout and confirmation URLs. (max 2000 characters)
   * @return push
  **/
  @ApiModelProperty(value = "URL that will be requested when an order is completed. Should be different than checkout and confirmation URLs. (max 2000 characters)")
  public String getPush() {
    return push;
  }

  public void setPush(String push) {
    this.push = push;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenMerchantUrls merchantUrls = (TokenMerchantUrls) o;
    return Objects.equals(this.confirmation, merchantUrls.confirmation) &&
        Objects.equals(this.push, merchantUrls.push);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmation, push);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenMerchantUrls {\n");
    
    sb.append("    confirmation: ").append(toIndentedString(confirmation)).append("\n");
    sb.append("    push: ").append(toIndentedString(push)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

