/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.model.checkout;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * Customer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-06T10:31:49.433Z")
public class Customer {
  @JsonProperty("date_of_birth")
  private String dateOfBirth = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("organization_registration_id")
  private String organizationRegistrationId = null;

  public Customer dateOfBirth(String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * ISO 8601 date. The customer date of birth.
   * @return dateOfBirth
  **/
  @ApiModelProperty(example = "1995-10-20", value = "ISO 8601 date. The customer date of birth.")
  public String getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public Customer type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The default supported value is &#39;person&#39;. If B2B is enabled for the merchant, the value may be \&quot;organization\&quot;.
   * @return type
  **/
  @ApiModelProperty(example = "person", value = "The default supported value is 'person'. If B2B is enabled for the merchant, the value may be \"organization\".")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Customer organizationRegistrationId(String organizationRegistrationId) {
    this.organizationRegistrationId = organizationRegistrationId;
    return this;
  }

   /**
   * The organization&#39;s official registration id (organization number). Applicable only for B2B orders
   * @return organizationRegistrationId
  **/
  @ApiModelProperty(example = "556737-0431", value = "The organization's official registration id (organization number). Applicable only for B2B orders")
  public String getOrganizationRegistrationId() {
    return organizationRegistrationId;
  }

  public void setOrganizationRegistrationId(String organizationRegistrationId) {
    this.organizationRegistrationId = organizationRegistrationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Customer customer = (Customer) o;
    return Objects.equals(this.dateOfBirth, customer.dateOfBirth) &&
        Objects.equals(this.type, customer.type) &&
        Objects.equals(this.organizationRegistrationId, customer.organizationRegistrationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateOfBirth, type, organizationRegistrationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    organizationRegistrationId: ").append(toIndentedString(organizationRegistrationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

