/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.api.payments.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PaymentsCustomer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-05T12:55:42.744Z")
public class PaymentsCustomer {
  @JsonProperty("date_of_birth")
  private String dateOfBirth = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("last_four_ssn")
  private String lastFourSsn = null;

  @JsonProperty("national_identification_number")
  private String nationalIdentificationNumber = null;

  /**
   * Organization entity type
   */
  public enum OrganizationEntityTypeEnum {
    LIMITED_COMPANY("LIMITED_COMPANY"),
    
    PUBLIC_LIMITED_COMPANY("PUBLIC_LIMITED_COMPANY"),
    
    ENTREPRENEURIAL_COMPANY("ENTREPRENEURIAL_COMPANY"),
    
    LIMITED_PARTNERSHIP_LIMITED_COMPANY("LIMITED_PARTNERSHIP_LIMITED_COMPANY"),
    
    LIMITED_PARTNERSHIP("LIMITED_PARTNERSHIP"),
    
    GENERAL_PARTNERSHIP("GENERAL_PARTNERSHIP"),
    
    REGISTERED_SOLE_TRADER("REGISTERED_SOLE_TRADER"),
    
    SOLE_TRADER("SOLE_TRADER"),
    
    CIVIL_LAW_PARTNERSHIP("CIVIL_LAW_PARTNERSHIP"),
    
    PUBLIC_INSTITUTION("PUBLIC_INSTITUTION"),
    
    OTHER("OTHER");

    private String value;

    OrganizationEntityTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OrganizationEntityTypeEnum fromValue(String text) {
      for (OrganizationEntityTypeEnum b : OrganizationEntityTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("organization_entity_type")
  private OrganizationEntityTypeEnum organizationEntityType = null;

  @JsonProperty("organization_registration_id")
  private String organizationRegistrationId = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("vat_id")
  private String vatId = null;

  public PaymentsCustomer dateOfBirth(String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * ISO 8601 date. The customer date of birth.
   * @return dateOfBirth
  **/
  @ApiModelProperty(value = "ISO 8601 date. The customer date of birth.")
  public String getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public PaymentsCustomer gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * The customer gender.
   * @return gender
  **/
  @ApiModelProperty(value = "The customer gender.")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public PaymentsCustomer lastFourSsn(String lastFourSsn) {
    this.lastFourSsn = lastFourSsn;
    return this;
  }

   /**
   * Last four digits for customer social security number
   * @return lastFourSsn
  **/
  @ApiModelProperty(value = "Last four digits for customer social security number")
  public String getLastFourSsn() {
    return lastFourSsn;
  }

  public void setLastFourSsn(String lastFourSsn) {
    this.lastFourSsn = lastFourSsn;
  }

  public PaymentsCustomer nationalIdentificationNumber(String nationalIdentificationNumber) {
    this.nationalIdentificationNumber = nationalIdentificationNumber;
    return this;
  }

   /**
   * The customer&#39;s national identification number
   * @return nationalIdentificationNumber
  **/
  @ApiModelProperty(value = "The customer's national identification number")
  public String getNationalIdentificationNumber() {
    return nationalIdentificationNumber;
  }

  public void setNationalIdentificationNumber(String nationalIdentificationNumber) {
    this.nationalIdentificationNumber = nationalIdentificationNumber;
  }

  public PaymentsCustomer organizationEntityType(OrganizationEntityTypeEnum organizationEntityType) {
    this.organizationEntityType = organizationEntityType;
    return this;
  }

   /**
   * Organization entity type
   * @return organizationEntityType
  **/
  @ApiModelProperty(value = "Organization entity type")
  public OrganizationEntityTypeEnum getOrganizationEntityType() {
    return organizationEntityType;
  }

  public void setOrganizationEntityType(OrganizationEntityTypeEnum organizationEntityType) {
    this.organizationEntityType = organizationEntityType;
  }

  public PaymentsCustomer organizationRegistrationId(String organizationRegistrationId) {
    this.organizationRegistrationId = organizationRegistrationId;
    return this;
  }

   /**
   * Organization registration id
   * @return organizationRegistrationId
  **/
  @ApiModelProperty(value = "Organization registration id")
  public String getOrganizationRegistrationId() {
    return organizationRegistrationId;
  }

  public void setOrganizationRegistrationId(String organizationRegistrationId) {
    this.organizationRegistrationId = organizationRegistrationId;
  }

  public PaymentsCustomer title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The customer&#39;s title
   * @return title
  **/
  @ApiModelProperty(value = "The customer's title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public PaymentsCustomer type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type
   * @return type
  **/
  @ApiModelProperty(value = "Type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public PaymentsCustomer vatId(String vatId) {
    this.vatId = vatId;
    return this;
  }

   /**
   * VAT id
   * @return vatId
  **/
  @ApiModelProperty(value = "VAT id")
  public String getVatId() {
    return vatId;
  }

  public void setVatId(String vatId) {
    this.vatId = vatId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentsCustomer customer = (PaymentsCustomer) o;
    return Objects.equals(this.dateOfBirth, customer.dateOfBirth) &&
        Objects.equals(this.gender, customer.gender) &&
        Objects.equals(this.lastFourSsn, customer.lastFourSsn) &&
        Objects.equals(this.nationalIdentificationNumber, customer.nationalIdentificationNumber) &&
        Objects.equals(this.organizationEntityType, customer.organizationEntityType) &&
        Objects.equals(this.organizationRegistrationId, customer.organizationRegistrationId) &&
        Objects.equals(this.title, customer.title) &&
        Objects.equals(this.type, customer.type) &&
        Objects.equals(this.vatId, customer.vatId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateOfBirth, gender, lastFourSsn, nationalIdentificationNumber, organizationEntityType, organizationRegistrationId, title, type, vatId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentsCustomer {\n");
    
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    lastFourSsn: ").append(toIndentedString(lastFourSsn)).append("\n");
    sb.append("    nationalIdentificationNumber: ").append(toIndentedString(nationalIdentificationNumber)).append("\n");
    sb.append("    organizationEntityType: ").append(toIndentedString(organizationEntityType)).append("\n");
    sb.append("    organizationRegistrationId: ").append(toIndentedString(organizationRegistrationId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    vatId: ").append(toIndentedString(vatId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

