/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.api.payments.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.klarna.rest.api.payments.model.PaymentsAuthorizedPaymentMethod;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * PaymentsErrorV2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-03T12:40:06.653Z")
public class PaymentsErrorV2 {
  @JsonProperty("authorized_payment_method_v1")
  private PaymentsAuthorizedPaymentMethod authorizedPaymentMethodV1 = null;

  @JsonProperty("correlation_id")
  private String correlationId = null;

  @JsonProperty("error_code")
  private String errorCode = null;

  @JsonProperty("error_messages")
  private List<String> errorMessages = null;

  @JsonProperty("fraud_status")
  private String fraudStatus = null;

  @JsonProperty("reason")
  private String reason = null;

  public PaymentsErrorV2 authorizedPaymentMethodV1(PaymentsAuthorizedPaymentMethod authorizedPaymentMethodV1) {
    this.authorizedPaymentMethodV1 = authorizedPaymentMethodV1;
    return this;
  }

   /**
   * Get authorizedPaymentMethodV1
   * @return authorizedPaymentMethodV1
  **/
  @ApiModelProperty(value = "")
  public PaymentsAuthorizedPaymentMethod getAuthorizedPaymentMethodV1() {
    return authorizedPaymentMethodV1;
  }

  public void setAuthorizedPaymentMethodV1(PaymentsAuthorizedPaymentMethod authorizedPaymentMethodV1) {
    this.authorizedPaymentMethodV1 = authorizedPaymentMethodV1;
  }

  public PaymentsErrorV2 correlationId(String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

   /**
   * Get correlationId
   * @return correlationId
  **/
  @ApiModelProperty(value = "")
  public String getCorrelationId() {
    return correlationId;
  }

  public void setCorrelationId(String correlationId) {
    this.correlationId = correlationId;
  }

  public PaymentsErrorV2 errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  @ApiModelProperty(value = "")
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public PaymentsErrorV2 errorMessages(List<String> errorMessages) {
    this.errorMessages = errorMessages;
    return this;
  }

  public PaymentsErrorV2 addErrorMessagesItem(String errorMessagesItem) {
    if (this.errorMessages == null) {
      this.errorMessages = new ArrayList<String>();
    }
    this.errorMessages.add(errorMessagesItem);
    return this;
  }

   /**
   * Get errorMessages
   * @return errorMessages
  **/
  @ApiModelProperty(value = "")
  public List<String> getErrorMessages() {
    return errorMessages;
  }

  public void setErrorMessages(List<String> errorMessages) {
    this.errorMessages = errorMessages;
  }

  public PaymentsErrorV2 fraudStatus(String fraudStatus) {
    this.fraudStatus = fraudStatus;
    return this;
  }

   /**
   * Get fraudStatus
   * @return fraudStatus
  **/
  @ApiModelProperty(value = "")
  public String getFraudStatus() {
    return fraudStatus;
  }

  public void setFraudStatus(String fraudStatus) {
    this.fraudStatus = fraudStatus;
  }

  public PaymentsErrorV2 reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @ApiModelProperty(value = "")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentsErrorV2 errorV2 = (PaymentsErrorV2) o;
    return Objects.equals(this.authorizedPaymentMethodV1, errorV2.authorizedPaymentMethodV1) &&
        Objects.equals(this.correlationId, errorV2.correlationId) &&
        Objects.equals(this.errorCode, errorV2.errorCode) &&
        Objects.equals(this.errorMessages, errorV2.errorMessages) &&
        Objects.equals(this.fraudStatus, errorV2.fraudStatus) &&
        Objects.equals(this.reason, errorV2.reason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authorizedPaymentMethodV1, correlationId, errorCode, errorMessages, fraudStatus, reason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentsErrorV2 {\n");
    
    sb.append("    authorizedPaymentMethodV1: ").append(toIndentedString(authorizedPaymentMethodV1)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorMessages: ").append(toIndentedString(errorMessages)).append("\n");
    sb.append("    fraudStatus: ").append(toIndentedString(fraudStatus)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

