/*
 * HPP
 * Hosted payment page
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.model.hosted_payment_page;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * SessionRequestV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-28T10:02:28.819Z")
public class SessionRequestV1 {
  @JsonProperty("merchant_urls")
  private MerchantUrlsV1 merchantUrls = null;

  @JsonProperty("options")
  private OptionsV1 options = null;

  @JsonProperty("payment_session_url")
  private String paymentSessionUrl = null;

  public SessionRequestV1 merchantUrls(MerchantUrlsV1 merchantUrls) {
    this.merchantUrls = merchantUrls;
    return this;
  }

   /**
   * Urls used to redirect the consumer
   * @return merchantUrls
  **/
  @ApiModelProperty(required = true, value = "Urls used to redirect the consumer")
  public MerchantUrlsV1 getMerchantUrls() {
    return merchantUrls;
  }

  public void setMerchantUrls(MerchantUrlsV1 merchantUrls) {
    this.merchantUrls = merchantUrls;
  }

  public SessionRequestV1 options(OptionsV1 options) {
    this.options = options;
    return this;
  }

   /**
   * Options
   * @return options
  **/
  @ApiModelProperty(value = "Options")
  public OptionsV1 getOptions() {
    return options;
  }

  public void setOptions(OptionsV1 options) {
    this.options = options;
  }

  public SessionRequestV1 paymentSessionUrl(String paymentSessionUrl) {
    this.paymentSessionUrl = paymentSessionUrl;
    return this;
  }

   /**
   * Url for the KP session
   * @return paymentSessionUrl
  **/
  @ApiModelProperty(example = "https://api.klarna.com/payments/v1/sessions/92d97f60-7a78-46a5-8f68-c56fe52dc4af", required = true, value = "Url for the KP session")
  public String getPaymentSessionUrl() {
    return paymentSessionUrl;
  }

  public void setPaymentSessionUrl(String paymentSessionUrl) {
    this.paymentSessionUrl = paymentSessionUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionRequestV1 sessionRequestV1 = (SessionRequestV1) o;
    return Objects.equals(this.merchantUrls, sessionRequestV1.merchantUrls) &&
        Objects.equals(this.options, sessionRequestV1.options) &&
        Objects.equals(this.paymentSessionUrl, sessionRequestV1.paymentSessionUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantUrls, options, paymentSessionUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionRequestV1 {\n");
    
    sb.append("    merchantUrls: ").append(toIndentedString(merchantUrls)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    paymentSessionUrl: ").append(toIndentedString(paymentSessionUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

