/*
 * HPP
 * Hosted payment page
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.model.hosted_payment_page;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * SessionStatusResponseV1
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-28T10:02:28.819Z")
public class SessionStatusResponseV1 {
  @JsonProperty("auth_token")
  private String authToken = null;

  /**
   * Current session status
   */
  public enum StatusEnum {
    WAITING("WAITING"),
    
    IN_PROGRESS("IN_PROGRESS"),
    
    COMPLETED("COMPLETED"),
    
    CANCELLED("CANCELLED"),
    
    FAILED("FAILED"),
    
    LEGACY("LEGACY");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("updated_at")
  private OffsetDateTime updatedAt = null;

  public SessionStatusResponseV1 authToken(String authToken) {
    this.authToken = authToken;
    return this;
  }

   /**
   * KP authorization token
   * @return authToken
  **/
  @ApiModelProperty(example = "b4bd3423-24e3", value = "KP authorization token")
  public String getAuthToken() {
    return authToken;
  }

  public void setAuthToken(String authToken) {
    this.authToken = authToken;
  }

  public SessionStatusResponseV1 status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Current session status
   * @return status
  **/
  @ApiModelProperty(example = "COMPLETED", value = "Current session status")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public SessionStatusResponseV1 updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Latest status update time
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2038-01-19T03:14:07.000Z", value = "Latest status update time")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SessionStatusResponseV1 sessionStatusResponseV1 = (SessionStatusResponseV1) o;
    return Objects.equals(this.authToken, sessionStatusResponseV1.authToken) &&
        Objects.equals(this.status, sessionStatusResponseV1.status) &&
        Objects.equals(this.updatedAt, sessionStatusResponseV1.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authToken, status, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SessionStatusResponseV1 {\n");
    
    sb.append("    authToken: ").append(toIndentedString(authToken)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

