/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.model.payments;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * AssetUrls
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-28T14:31:36.430Z")
public class AssetUrls {
  @JsonProperty("descriptive")
  private String descriptive = null;

  @JsonProperty("standard")
  private String standard = null;

  public AssetUrls descriptive(String descriptive) {
    this.descriptive = descriptive;
    return this;
  }

   /**
   * Decriptive asset URL
   * @return descriptive
  **/
  @ApiModelProperty(example = "https://cdn.klarna.com/1.0/shared/image/generic/badge/en_us/pay_later/descriptive/pink.svg", value = "Decriptive asset URL")
  public String getDescriptive() {
    return descriptive;
  }

  public void setDescriptive(String descriptive) {
    this.descriptive = descriptive;
  }

  public AssetUrls standard(String standard) {
    this.standard = standard;
    return this;
  }

   /**
   * Standard asset URL
   * @return standard
  **/
  @ApiModelProperty(example = "https://cdn.klarna.com/1.0/shared/image/generic/badge/en_us/pay_later/standard/pink.svg", value = "Standard asset URL")
  public String getStandard() {
    return standard;
  }

  public void setStandard(String standard) {
    this.standard = standard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetUrls assetUrls = (AssetUrls) o;
    return Objects.equals(this.descriptive, assetUrls.descriptive) &&
        Objects.equals(this.standard, assetUrls.standard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descriptive, standard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetUrls {\n");
    
    sb.append("    descriptive: ").append(toIndentedString(descriptive)).append("\n");
    sb.append("    standard: ").append(toIndentedString(standard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

