/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.model.payments;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * CustomerTokenCreationResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-28T14:31:36.430Z")
public class CustomerTokenCreationResponse {
  @JsonProperty("token_id")
  private String tokenId = null;

  @JsonProperty("redirect_url")
  private String redirectUrl = null;

  public CustomerTokenCreationResponse tokenId(String tokenId) {
    this.tokenId = tokenId;
    return this;
  }

   /**
   * Used when placing the order
   * @return tokenId
  **/
  @ApiModelProperty(example = "0b1d9815-165e-42e2-8867-35bc03789e00", required = true, value = "Used when placing the order")
  public String getTokenId() {
    return tokenId;
  }

  public void setTokenId(String tokenId) {
    this.tokenId = tokenId;
  }

  public CustomerTokenCreationResponse redirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
    return this;
  }

   /**
   * URL to redirect the customer to after placing the order.
   * @return redirectUrl
  **/
  @ApiModelProperty(example = "https://credit.klarna.com/v1/sessions/0b1d9815-165e-42e2-8867-35bc03789e00/redirect", required = true, value = "URL to redirect the customer to after placing the order.")
  public String getRedirectUrl() {
    return redirectUrl;
  }

  public void setRedirectUrl(String redirectUrl) {
    this.redirectUrl = redirectUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerTokenCreationResponse customerTokenCreationResponse = (CustomerTokenCreationResponse) o;
    return Objects.equals(this.tokenId, customerTokenCreationResponse.tokenId) &&
        Objects.equals(this.redirectUrl, customerTokenCreationResponse.redirectUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenId, redirectUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerTokenCreationResponse {\n");
    
    sb.append("    tokenId: ").append(toIndentedString(tokenId)).append("\n");
    sb.append("    redirectUrl: ").append(toIndentedString(redirectUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

