/*
 * Klarna Settlements API
 * This API gives you access to your payouts and transactions.     Resources are split into two broad types:     * Collections, including pagination information:      collections are queryable, typically by the attributes of the sub-resource      as well as pagination.    * Entity resources containing a single entity.
 *
 * OpenAPI spec version: 1.0.0-rc2
 * Contact: integration@klarna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.api.settlements.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.klarna.rest.api.settlements.model.SettlementsPagination;
import com.klarna.rest.api.settlements.model.SettlementsPayout;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SettlementsPayoutCollection
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-20T11:18:02.332Z")
public class SettlementsPayoutCollection {
  @JsonProperty("payouts")
  private List<SettlementsPayout> payouts = new ArrayList<SettlementsPayout>();

  @JsonProperty("pagination")
  private SettlementsPagination pagination = null;

  public SettlementsPayoutCollection payouts(List<SettlementsPayout> payouts) {
    this.payouts = payouts;
    return this;
  }

  public SettlementsPayoutCollection addPayoutsItem(SettlementsPayout payoutsItem) {
    this.payouts.add(payoutsItem);
    return this;
  }

   /**
   * Get payouts
   * @return payouts
  **/
  @ApiModelProperty(required = true, value = "")
  public List<SettlementsPayout> getPayouts() {
    return payouts;
  }

  public void setPayouts(List<SettlementsPayout> payouts) {
    this.payouts = payouts;
  }

  public SettlementsPayoutCollection pagination(SettlementsPagination pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  @ApiModelProperty(required = true, value = "")
  public SettlementsPagination getPagination() {
    return pagination;
  }

  public void setPagination(SettlementsPagination pagination) {
    this.pagination = pagination;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettlementsPayoutCollection payoutCollection = (SettlementsPayoutCollection) o;
    return Objects.equals(this.payouts, payoutCollection.payouts) &&
        Objects.equals(this.pagination, payoutCollection.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payouts, pagination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettlementsPayoutCollection {\n");
    
    sb.append("    payouts: ").append(toIndentedString(payouts)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

