/*
 * Klarna Order Managment API
 * API to handle order lifecycle
 *
 * OpenAPI spec version: 1.0
 * Contact: developers-experience@klarna.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.klarna.rest.model.order_management;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * UpdateShippingInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-06T11:24:04.099Z")
public class UpdateShippingInfo {
  @JsonProperty("shipping_info")
  private List<ShippingInfo> shippingInfo = new ArrayList<ShippingInfo>();

  public UpdateShippingInfo shippingInfo(List<ShippingInfo> shippingInfo) {
    this.shippingInfo = shippingInfo;
    return this;
  }

  public UpdateShippingInfo addShippingInfoItem(ShippingInfo shippingInfoItem) {
    this.shippingInfo.add(shippingInfoItem);
    return this;
  }

   /**
   * New shipping info. Maximum: 500 items.
   * @return shippingInfo
  **/
  @ApiModelProperty(required = true, value = "New shipping info. Maximum: 500 items.")
  public List<ShippingInfo> getShippingInfo() {
    return shippingInfo;
  }

  public void setShippingInfo(List<ShippingInfo> shippingInfo) {
    this.shippingInfo = shippingInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateShippingInfo updateShippingInfo = (UpdateShippingInfo) o;
    return Objects.equals(this.shippingInfo, updateShippingInfo.shippingInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shippingInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateShippingInfo {\n");
    
    sb.append("    shippingInfo: ").append(toIndentedString(shippingInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

